
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/openshift/api/route/v1",
  "github.com/micro/go-config",
  "github.com/fsnotify/fsnotify",
  "github.com/pborman/uuid",
  "bitbucket.org/atlassian/go-stride/pkg/stride",
  "github.com/appscode/envconfig",
]

[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.9.3"
  revision = "91d3f6a57905178524105a085085901bb73bd3dc"

[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.9.3"
  revision = "acf347b865f29325eb61f4cd2df11e86e073a5ee"

[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.9.3"
  revision = "19e3f5aa3adca672c153d324e6b7d82ff8935f03"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.9.3"
  revision = "9389c055a838d4f208b699b3c7c51b70f2368861"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  #branch = "v0.0.5"
  version = "v0.0.5"

[[constraint]]
  name = "github.com/openshift/api"
  version = "3.9.0"

[[constraint]]
  name = "github.com/micro/go-config"
  version = "0.7.0"
